routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(app()->getLocale());
});

Route::get('/import-products', 'ProductController@import')->name('import_products');


Route::group(['prefix' => '{locale}', 'as' => 'localized.', 'where' => ['locale' => 'ru|uk'], 'middleware' => 'setlocale'], function () {
    Route::get('/welcome', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('/product/{id}', 'ProductController@show')->name('product');

    Route::get('/products', 'ProductController@index')->name('products');

    Route::get('/', function () {
        return view('home');
    })->name('home');


});

app/Product.php
<?php

namespace App;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements TranslatableContract
{
    use Translatable;

    public $translatedAttributes = ['name', 'description'];

    public $fillable = ['sku', 'price'];

    public function characteristics()
    {
        return $this->hasMany(ProductCharacteristic::class);
    }

    public function getPriceAttribute($price)
    {
        return $price * 100;
    }
}

app/ProductCharacteristic.php
<?php

namespace App;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class ProductCharacteristic extends Model implements TranslatableContract
{
    use Translatable;

    public $translatedAttributes = ['name', 'value'];
}

app/ProductCharacteristicTranslation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductCharacteristicTranslation extends Model
{
    protected $fillable = ['name', 'value'];
    public $timestamps = false;
}

app/ProductTranslation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductTranslation extends Model
{
    protected $fillable = ['name', 'description'];
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductsImportRequest;
use App\Product;
use App\Services\Product\ImportService;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::paginate(15);

        return view('product.index', ['models' => $products]);
    }

    public function show($locale, $id)
    {
        return view('product.show', ['model' => Product::findOrFail(['id' => $id])->first()]);
    }

    /**
     * @param ImportService $importService
     * @param ProductsImportRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function import(ImportService $importService, ProductsImportRequest $request)
    {
        $importService->process($request->getProductsSource());

        return redirect(route('localized.products', app()->getLocale()));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        <form method="GET" action="{{ route('import_products') }}">
                            <button id="import" type="submit" name="source" value="sandi"
                                    class="btn btn-primary btn-lg"><i class='fa fa-spinner fa-spin'></i>Start import
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('localized.welcome', app()->getLocale()) }}">Welcome</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('localized.products', app()->getLocale()) }}">Products</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @foreach (config('app.available_locales') as $locale)
                        <?php
                        \Illuminate\Support\Facades\Route::current()->setParameter('locale',$locale);
                        ?>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ route(\Illuminate\Support\Facades\Route::currentRouteName(), \Illuminate\Support\Facades\Route::current()->parameters()) }}"
                               @if (app()->getLocale() == $locale) style="font-weight: bold; text-decoration: underline" @endif>{{ strtoupper($locale) }}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Products</div>
                    <div class="card-body">
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @foreach ($models as $model)
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="{{ route('localized.product', [app()->getLocale(), $model->id]) }}">{{ $model->name }}</a>
                                </li>
                            @endforeach
                        </ul>
                        {{ $models->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{$model->name}} <b class="">( @money($model->price, 'UAH') )</b></div>

                    <div class="card-body">
                        <p>{{$model->description}}</p>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($model->characteristics as $characteristic)
                                <tr>
                                    <td>
                                        {{ $characteristic->name }}
                                    </td>
                                    <td>
                                        {{ $characteristic->value }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection